---
- hosts: all
  become: true
  tasks:
    - name: update repository index
      apt:
        update_cache: yes
    - name: install apache2 httpd package
      apt:
        name: apache2
        state: latest
        # state: present # optional
    - name: add php support for apache
      apt:
        name: libapache2-mod-php
        state: latest
